export const GET_TEAMS = 'GET_TEAMS';
export const STATUS_GET_TEAMS = 'STATUS_GET_TEAMS';
export const GET_TEAM_STATS = 'GET_TEAM_STATS';
export const STATUS_GET_TEAM_STATS = 'STATUS_GET_TEAM_STATS';
export const SET_ACTIVE_TEAM = 'SET_ACTIVE_TEAM';

export const GET_ROSTER = 'GET_ROSTER';
export const STATUS_GET_ROSTER = 'STATUS_GET_ROSTER';

export const GET_PLAYER = 'GET_PLAYER';
export const STATUS_GET_PLAYER = 'STATUS_GET_PLAYER';
export const GET_PLAYER_STATS = 'GET_PLAYER_STATS';
export const STATUS_GET_PLAYER_STATS = 'STATUS_GET_PLAYER_STATS';

export const GET_DIVISIONS = 'GET_DIVISIONS';
export const STATUS_GET_DIVISIONS = 'STATUS_GET_DIVISIONS';

export const GET_CONFERENCES = 'GET_CONFERENCES';
export const STATUS_GET_CONFERENCES = 'STATUS_GET_CONFERENCES';

export const GET_SCHEDULE = 'GET_SCHEDULE';
export const STATUS_GET_SCHEDULE = 'STATUS_GET_SCHEDULE';
